services:
  php:
    build:
      context: .
      target: runner
      args:
        PHP_VERSION: 8.5.1
    user: "${UID}:${GID}"
    entrypoint: ["php"]
    volumes:
      - .:/app

  composer:
    extends: php
    entrypoint: ["composer"]
